theme: jekyll-theme-cayman
title: Soumi Das
description: Ph.D Scholar at C.S.E Department, IIT KGP
avatar: https://github.com/SoumiDas/SoumiDas.github.io/blob/master/13041240_10207953920959394_9206261717483753467_o.jpg
twitter_username: soumi_das0407
