theme: jekyll-theme-cayman
title: Soumi Das
description: Post Doctoral Researcher at MPI-SWS, Saarbrucken
avatar: https://github.com/SoumiDas/SoumiDas.github.io/docs/assets/13041240_10207953920959394_9206261717483753467_o.jpg
twitter_username: soumi_das0407
